### PR TITLE
Bootstrap fix

### PR DESCRIPTION
**Pull request by mminutel**
I think I'm doing this whole Git thing right, but I'm not sure. Anyway, take a look at this, and we can discuss tomorrow.

It seems like you're messing the Bootstrap up a bit here. The Grid should usually only be defined once in your project. Sometimes it gets used in the Nav/Footer as well, but it really just defines your overall containing space. 

Then when it comes to the grid system, Columns need to be children of Rows. You should never have the case where you just define a row and not have child columns.

I think the changes to the Navigation is close to what you were going for, but it's still not quite right since 
pricing, blog, and support are not right aligned like you had them, but the way you had the navbar structured was keeping everything from being inline. There was also that strange anchor tag that was getting added to your form which caused the cursor to change to pointer if you hover over the spot just under the search box.

Let me know what you think!

### CODE REVIEW

**Comment by JasonKDarby** [comment]
I'll be reviewing this tonight, but thanks!  I really don't know a ton about bootstrap itself so this is definitely appreciated.

**Comment by JasonKDarby** [comment]
Regarding columns without rows, I really wasn't sure because I didn't see a difference.  I thought row was implicit if there are columns and that possibly you just needed row explicitly defined if there were multiple.  Again, just a suspicion.

**Comment by JasonKDarby** [comment]
I'll look for docs on Grid, it seems unintuitive that you should only have it once.

**Comment by mminutel** [comment]
All the Grid element is doing is defining a Bootstrap .container which is basically just adding a div with some defined width to define your boundaries. There's nothing to stop you from defining it multiple places, and it wouldn't be "wrong". It's just very unnecessary unless you need to have different "sections" of your application to be fluid and others to be static. Typically, you would see that tag used in the header, footer, and then the main body, but even that is unnecessary if your header, footer, and body are all fluid or static.

**Comment by mminutel** [comment]
As for the row/column thing, a row will define some negative margin on the left/right to makeup for the "gutters" (left/right margins on the columns), so it's effectively "deleting" the left margin on the first column and the right margin on the last column. If you use a row without defining columns, the elements you define in the row are going to be shifted to the left and break the alignment of the elements when you actually do use columns.

**Comment by JasonKDarby** [comment]
This says to me that those sections that I factored out should be just part of App.  I don't like the idea of assuming the outside of the subset, in my mind it's equivalent to a side effect

**Comment by JasonKDarby** [comment]
I've looked more into this and I see your point regarding `Grid` just being `.container` and nested `.container` isn't really a thing.  I don't fully understand the details regarding the margins but I don't think it's relevant to the solution.  I need to understand the right way to implement something like `who` in App/index.js.  If it's correct to assume that `<Grid>` exists outside of `who` then I don't like it but I'll suck it up and go with it but I need to be sure of that.  Again, maybe it's more correct to just put all of the static, use 1 time, things into `App`.  Then `App` would define `<Grid>` and everything would make sense to me.

**Pull request closed without merging**
